### ISSUE TITLE
Service Discovery support?

### ISSUE THREAD

**Issue by dt** [flier/curator.go#2]
The examples section of the README mentions service discovery, but it looks like there isn't any actual code related to service discovery checked in yet. Is this work in-progress or otherwise planned?

I might work on it if not, but just wanted to make sure it wasn't already in-progress or done somewhere else before I started.

**Comment by zj8487** [comment]
any progress?

**Comment by dt** [comment]
Since this project looked abandoned, I ended up implementing it here instead: https://github.com/foursquare/fsgo/tree/master/net/discovery

**Comment by dt** [comment]
(example usage: https://github.com/foursquare/quiver/blob/master/discovery.go )

**Comment by zj8487** [comment]
@dt 
thanks a lot
